/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/res/layout/reminders_main_activity.xml
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/res/layout/reminder_add.xml
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/res/values/strings.xml
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/framework/persistence/GenericDAO.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/ReminderMainActivity.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/controller/Controller.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/model/Reminder.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/model/cp/ReminderContentProvider.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/model/db/DBConstants.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/model/db/DBFactory.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/model/db/DBHelper.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/model/db/DefaultDBFactory.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/model/db/DefaultReminderDAO.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/view/AddReminderActivity.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/view/EditReminderActivity.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/view/ExternalAddReminderActivity.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/view/ReminderActivity.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/view/ReminderAddActivity.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/view/ReminderFilterArrayAdapter.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/view/ReminderListFragment.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/model/db/ReminderDAO.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/model/db/CategoryDAO.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/model/db/DefaultCategoryDAO.java
/home/leomarcamargo/workspace/eclipse/android-neon/reminder-cc-2.0/static-category/src/br/unb/cic/reminders/view/FilterListFragment.java
